import { Router, type IRouter } from "express";
import healthRouter from "./health";
import projectsRouter from "./projects";
import membersRouter from "./members";
import tasksRouter from "./tasks";
import sprintsRouter from "./sprints";
import timeEntriesRouter from "./time-entries";
import goalsRouter from "./goals";
import announcementsRouter from "./announcements";
import documentsRouter from "./documents";
import dashboardRouter from "./dashboard";
import aiRouter from "./ai";
import taskCommentsRouter from "./task-comments";
import activityRouter from "./activity";
import notificationsRouter from "./notifications";
import expensesRouter from "./expenses";
import taskTemplatesRouter from "./task-templates";
import customFieldsRouter from "./custom-fields";
import adminRouter from "./admin";
import apiKeysRouter from "./api-keys";
import messagingRouter from "./messaging";
import remindersRouter from "./reminders";
import emailRoutingRouter from "./email-routing";
import calendarRouter from "./calendar";
import invoicesRouter from "./finance/invoices";
import portfoliosRouter from "./finance/portfolios";
import transactionsRouter from "./finance/transactions";
import virtualCardsRouter from "./finance/virtual-cards";
import financeDocsRouter from "./finance/api-docs";
import emailProjectsRouter from "./email-projects";
import taskDependenciesRouter from "./task-dependencies";
import automationsRouter from "./automations";
import formsRouter from "./forms";
import milestonesRouter from "./milestones";
import approvalsRouter from "./approvals";
import projectUpdatesRouter from "./project-updates";
import savedViewsRouter from "./saved-views";
import favoritesRouter from "./favorites";
import workloadRouter from "./workload";
import projectTemplatesRouter from "./project-templates";
import tagsRouter from "./tags";
import outgoingWebhooksRouter from "./outgoing-webhooks";
import reportsRouter from "./reports";
import taskAttachmentsRouter from "./task-attachments";
import automationRunsRouter from "./automation-runs";
import taskLinksRouter from "./task-links";
import trashRouter from "./trash";
import userPreferencesRouter from "./user-preferences";
import guestsRouter from "./guests";
import dashboardWidgetsRouter from "./dashboard-widgets";
import searchRouter from "./search";
import importExportRouter from "./import-export";
import taskProjectsRouter from "./task-projects";
import sharedViewsRouter from "./shared-views";
import emailImportRouter from "./email-import";
import fastmailRouter from "./fastmail";
import aiAgentsRouter from "./ai-agents";
import aiWorkflowsRouter from "./ai-workflows";
import flowchartsRouter from "./flowcharts";
import smartScheduleRouter from "./smart-schedule";
import retrospectivesRouter from "./retrospectives";
import changelogRouter from "./changelog";
import workspaceAnalyticsRouter from "./workspace-analytics";
import urgentTasksEmailRouter from "./urgent-tasks-email";
import connectionsMonitorRouter from "./connections-monitor";

const router: IRouter = Router();

router.use(healthRouter);
router.use(projectsRouter);
router.use(membersRouter);
router.use(tasksRouter);
router.use(sprintsRouter);
router.use(timeEntriesRouter);
router.use(goalsRouter);
router.use(announcementsRouter);
router.use(documentsRouter);
router.use(dashboardRouter);
router.use(aiRouter);
router.use(taskCommentsRouter);
router.use(activityRouter);
router.use(notificationsRouter);
router.use(expensesRouter);
router.use(taskTemplatesRouter);
router.use(customFieldsRouter);
router.use(adminRouter);
router.use(apiKeysRouter);
router.use(messagingRouter);
router.use(remindersRouter);
router.use(emailRoutingRouter);
router.use(calendarRouter);
router.use(invoicesRouter);
router.use(portfoliosRouter);
router.use(transactionsRouter);
router.use(virtualCardsRouter);
router.use(financeDocsRouter);
router.use(emailProjectsRouter);
router.use(taskDependenciesRouter);
router.use(automationsRouter);
router.use(formsRouter);
router.use(milestonesRouter);
router.use(approvalsRouter);
router.use(projectUpdatesRouter);
router.use(savedViewsRouter);
router.use(favoritesRouter);
router.use(workloadRouter);
router.use(projectTemplatesRouter);
router.use(tagsRouter);
router.use(outgoingWebhooksRouter);
router.use(reportsRouter);
router.use(taskAttachmentsRouter);
router.use(automationRunsRouter);
router.use(taskLinksRouter);
router.use(trashRouter);
router.use(userPreferencesRouter);
router.use(guestsRouter);
router.use(dashboardWidgetsRouter);
router.use(searchRouter);
router.use(importExportRouter);
router.use(taskProjectsRouter);
router.use(sharedViewsRouter);
router.use(emailImportRouter);
router.use(fastmailRouter);
router.use(aiAgentsRouter);
router.use(aiWorkflowsRouter);
router.use(flowchartsRouter);
router.use(smartScheduleRouter);
router.use(retrospectivesRouter);
router.use(changelogRouter);
router.use(workspaceAnalyticsRouter);
router.use(urgentTasksEmailRouter);
router.use(connectionsMonitorRouter);

export default router;
