import { Router, type IRouter } from "express";
import healthRouter from "./health";
import projectsRouter from "./projects";
import membersRouter from "./members";
import tasksRouter from "./tasks";
import sprintsRouter from "./sprints";
import timeEntriesRouter from "./time-entries";
import goalsRouter from "./goals";
import announcementsRouter from "./announcements";
import documentsRouter from "./documents";
import dashboardRouter from "./dashboard";
import aiRouter from "./ai";
import taskCommentsRouter from "./task-comments";
import activityRouter from "./activity";
import notificationsRouter from "./notifications";
import expensesRouter from "./expenses";
import taskTemplatesRouter from "./task-templates";
import customFieldsRouter from "./custom-fields";
import adminRouter from "./admin";
import apiKeysRouter from "./api-keys";
import messagingRouter from "./messaging";
import remindersRouter from "./reminders";
import emailRoutingRouter from "./email-routing";
import calendarRouter from "./calendar";
import invoicesRouter from "./finance/invoices";
import portfoliosRouter from "./finance/portfolios";
import transactionsRouter from "./finance/transactions";
import virtualCardsRouter from "./finance/virtual-cards";

const router: IRouter = Router();

router.use(healthRouter);
router.use(projectsRouter);
router.use(membersRouter);
router.use(tasksRouter);
router.use(sprintsRouter);
router.use(timeEntriesRouter);
router.use(goalsRouter);
router.use(announcementsRouter);
router.use(documentsRouter);
router.use(dashboardRouter);
router.use(aiRouter);
router.use(taskCommentsRouter);
router.use(activityRouter);
router.use(notificationsRouter);
router.use(expensesRouter);
router.use(taskTemplatesRouter);
router.use(customFieldsRouter);
router.use(adminRouter);
router.use(apiKeysRouter);
router.use(messagingRouter);
router.use(remindersRouter);
router.use(emailRoutingRouter);
router.use(calendarRouter);
router.use(invoicesRouter);
router.use(portfoliosRouter);
router.use(transactionsRouter);
router.use(virtualCardsRouter);

export default router;
