import { pgTable, text, serial, timestamp, integer, numeric, boolean, jsonb, index } from "drizzle-orm/pg-core";

export const invoicesTable = pgTable("invoices", {
  id: serial("id").primaryKey(),
  invoiceNumber: text("invoice_number").notNull().unique(),
  status: text("status").notNull().default("draft"),
  fromName: text("from_name").notNull(),
  fromEmail: text("from_email").notNull(),
  toName: text("to_name").notNull(),
  toEmail: text("to_email").notNull(),
  toAddress: text("to_address"),
  currency: text("currency").notNull().default("USD"),
  subtotal: numeric("subtotal", { precision: 12, scale: 2 }).notNull().default("0"),
  taxRate: numeric("tax_rate", { precision: 5, scale: 2 }).default("0"),
  taxAmount: numeric("tax_amount", { precision: 12, scale: 2 }).default("0"),
  discount: numeric("discount", { precision: 12, scale: 2 }).default("0"),
  total: numeric("total", { precision: 12, scale: 2 }).notNull().default("0"),
  amountPaid: numeric("amount_paid", { precision: 12, scale: 2 }).default("0"),
  amountDue: numeric("amount_due", { precision: 12, scale: 2 }).notNull().default("0"),
  issuedAt: timestamp("issued_at", { withTimezone: true }),
  dueAt: timestamp("due_at", { withTimezone: true }),
  paidAt: timestamp("paid_at", { withTimezone: true }),
  notes: text("notes"),
  terms: text("terms"),
  isRecurring: boolean("is_recurring").default(false),
  recurringInterval: text("recurring_interval"),
  nextRecurringDate: timestamp("next_recurring_date", { withTimezone: true }),
  parentInvoiceId: integer("parent_invoice_id"),
  metadata: jsonb("metadata"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  index("invoices_status_idx").on(t.status),
  index("invoices_to_email_idx").on(t.toEmail),
  index("invoices_due_at_idx").on(t.dueAt),
]);

export const invoiceLineItemsTable = pgTable("invoice_line_items", {
  id: serial("id").primaryKey(),
  invoiceId: integer("invoice_id").notNull().references(() => invoicesTable.id, { onDelete: "cascade" }),
  description: text("description").notNull(),
  quantity: numeric("quantity", { precision: 10, scale: 2 }).notNull().default("1"),
  unitPrice: numeric("unit_price", { precision: 12, scale: 2 }).notNull(),
  amount: numeric("amount", { precision: 12, scale: 2 }).notNull(),
  sortOrder: integer("sort_order").default(0),
});

export const portfoliosTable = pgTable("portfolios", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  description: text("description"),
  currency: text("currency").notNull().default("USD"),
  totalValue: numeric("total_value", { precision: 14, scale: 2 }).default("0"),
  totalCost: numeric("total_cost", { precision: 14, scale: 2 }).default("0"),
  gainLoss: numeric("gain_loss", { precision: 14, scale: 2 }).default("0"),
  gainLossPercent: numeric("gain_loss_percent", { precision: 8, scale: 2 }).default("0"),
  metadata: jsonb("metadata"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const portfolioHoldingsTable = pgTable("portfolio_holdings", {
  id: serial("id").primaryKey(),
  portfolioId: integer("portfolio_id").notNull().references(() => portfoliosTable.id, { onDelete: "cascade" }),
  symbol: text("symbol").notNull(),
  name: text("name").notNull(),
  assetType: text("asset_type").notNull().default("stock"),
  quantity: numeric("quantity", { precision: 14, scale: 6 }).notNull(),
  avgCost: numeric("avg_cost", { precision: 12, scale: 2 }).notNull(),
  currentPrice: numeric("current_price", { precision: 12, scale: 2 }),
  totalCost: numeric("total_cost", { precision: 14, scale: 2 }).notNull(),
  currentValue: numeric("current_value", { precision: 14, scale: 2 }),
  gainLoss: numeric("gain_loss", { precision: 14, scale: 2 }),
  gainLossPercent: numeric("gain_loss_percent", { precision: 8, scale: 2 }),
  metadata: jsonb("metadata"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  index("holdings_portfolio_idx").on(t.portfolioId),
  index("holdings_symbol_idx").on(t.symbol),
]);

export const transactionsTable = pgTable("finance_transactions", {
  id: serial("id").primaryKey(),
  type: text("type").notNull(),
  category: text("category"),
  description: text("description").notNull(),
  amount: numeric("amount", { precision: 12, scale: 2 }).notNull(),
  currency: text("currency").notNull().default("USD"),
  fromAccount: text("from_account"),
  toAccount: text("to_account"),
  reference: text("reference"),
  status: text("status").notNull().default("completed"),
  portfolioId: integer("portfolio_id"),
  invoiceId: integer("invoice_id"),
  virtualCardId: text("virtual_card_id"),
  privacyTransactionToken: text("privacy_transaction_token"),
  metadata: jsonb("metadata"),
  transactedAt: timestamp("transacted_at", { withTimezone: true }).notNull().defaultNow(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  index("transactions_type_idx").on(t.type),
  index("transactions_category_idx").on(t.category),
  index("transactions_status_idx").on(t.status),
  index("transactions_date_idx").on(t.transactedAt),
]);

export const virtualCardsTable = pgTable("virtual_cards", {
  id: serial("id").primaryKey(),
  privacyCardToken: text("privacy_card_token").notNull().unique(),
  lastFour: text("last_four"),
  cardName: text("card_name"),
  memo: text("memo"),
  type: text("type").notNull().default("SINGLE_USE"),
  state: text("state").notNull().default("OPEN"),
  spendLimit: numeric("spend_limit", { precision: 12, scale: 2 }),
  spendLimitDuration: text("spend_limit_duration"),
  totalSpent: numeric("total_spent", { precision: 12, scale: 2 }).default("0"),
  hostname: text("hostname"),
  metadata: jsonb("metadata"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  index("vcards_state_idx").on(t.state),
  index("vcards_privacy_token_idx").on(t.privacyCardToken),
]);
